# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mississippi', '0004_auto_20170522_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteresource',
            name='views',
        ),
    ]
